### ISSUE TITLE
Problem building after upgrading to 5.0.0

### ISSUE THREAD

**Issue by NickHoath** [atteneder/glTFast#550]
**Describe the bug**
I've upgraded our version of glTFast to 5.0.0. When building I get the following error:
Library/PackageCache/com.atteneder.gltfast@5.0.0/Runtime/Scripts/GltfImport.cs(397,13): error CS0518: Predefined type 'System.IAsyncDisposable' is not defined or imported
This is with Unity 2021.3.6f1. I have tried going to latest LTS, but still have the same problem. Commenting out the 'await using' allows the build to proceed and the library appears to still work.
However, as we use automated build, I can't patch the library for each build :/

**Comment by JSWorkspace1** [comment]
I have the same Problem
Unity: 2021.3.16f1
Scripting backend: Mono 
 Api Compatibility Level. .NET Framework

**Comment by atteneder** [comment]
Hi and thanks a lot for reporting.

For reasons unknown to me I couldn't reproduce the issue. What Editor and target platforms are you working on?

The [docs](https://learn.microsoft.com/en-us/dotnet/api/system.iasyncdisposable?view=net-7.0&viewFallbackFrom=netframework-4.8) say that `IAsyncDisposable` is indeed not part of .NET Framework 4.8 (but it is available in .NET Standard 2.1), so that seems to be the problem.

Could any of you be so kind and confirm that this snippet fixes the issue?

```csharp
#if UNITY_2021_3_OR_NEWER && NET_STANDARD_2_1
            await using
#endif
            var fs = new FileStream(localPath, FileMode.Open, FileAccess.Read);
```

Thanks!

**Comment by NickHoath** [comment]
Hi. Yes, that does indeed fix the issue!

**Comment by msimtmv** [comment]
Hello! Any prediction on when fixes like this would be included in the OpenUPM installer package?

**Comment by nda051088** [comment]
For me, this issue still persists. I am using unity version 2021.3.11f1 and API is .Net Standard 2.1. I still have to comment out the code "await using " to make a build. Thanks in advance.

**Comment by DWRDV** [comment]
Await using appears to be unnecessary, if not deprecated. So what precisely is the line being used to do? The underlying file stream shouldn't need cleanup from the old .net standard, @atteneder, although I could have misunderstood its purpose.

**Comment by DevinLFL** [comment]
Hi, we're the same error  `CS0518: Predefined type 'System.IAsyncDisposable' ` even with `NET_STANDARD_2_1` added to the IF statement. Weirdly though we don't have the compile problem on Mac's it's only windows machines and Unity Cloud Build which is extra strange because unity WebGL is build on a mac according to the config. 

Adding 
`namespace System
{
    public enum IAsyncDisposable
    {
    }
}`

To the bottom of the file works to fix the compiler error but it feels like a massive hack.
